[server]
host = "server.com"
user = "root"
port = 22

# Testing Redirects and SSL Certificates
[[redirects]]
target_url = "https://github.com/"
site_urls = [
    'http://github.de',
    'http://www.github.com',
    'https://www.github.com',
]


[database.localdb]
image = "postgres:10"
backup_dir="${pwd}/backup"

remote_user="remote_user"
remote_password="remote_password"
remote_database="remote_database"
remote_host="remote_host"
remote_port="5432"

local_user="local_user"
local_database="local_database"
local_password="local_password"
local_port="5432"


[containers.dnsdock]
name = "dnsdock"
image = "tonistiigi/dnsdock"
volumes = [
    "/var/run/docker.sock:/var/run/docker.sock",
]
ports = [
    "172.17.42.1:53:53/udp"
]

[containers.redis]
name = "redis"
image = "redis"
environments = [
    "DNSDOCK_NAME=staging",
    "DNSDOCK_IMAGE=redis"
]

[containers.app_1]
name = "app_1"
build = "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/steffenmllr/cloaked-batman.git"
branch = "master"
code_dir = "/tmp/app_1"
hook_before_deploy="before_deploy"
hook_atfer_deploy="after_deploy"
environments = [
    "NODE_ENV=staging",
    "DNSDOCK_NAME=staging",
    "DNSDOCK_IMAGE=app_1"
]

[containers.app_2]
name = "app_1"
build = "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/steffenmllr/cloaked-batman.git"
branch = "master"
code_dir = "${pwd}/local/app_2"
environments = [
    "NODE_ENV=staging",
    "DNSDOCK_NAME=staging",
    "DNSDOCK_IMAGE=app_2"
]
